[workspace]
resolver = "2"
members = [
  "components/aegis-common",
  "components/aegis-shell",
  "components/aegis-dock",
  "components/aegis-tour",
  "components/aegis-installer",
  "components/aegis-pkg",
]
default-members = ["components/aegis-common"]

[workspace.package]
version = "1.0.15"
edition = "2021"
license = "GPL-3.0-only"
repository = "https://github.com/AegisOperativeSystem/aegis-os"

[workspace.dependencies]
gtk4 = { version = "0.11", features = ["v4_12"] }
aegis-common = { path = "components/aegis-common" }
